# Numpy

In [1]:
import numpy

In [2]:
numpy.version

<module 'numpy.version' from 'C:\\Users\\Sasha\\anaconda3\\lib\\site-packages\\numpy\\version.py'>

In [3]:
import numpy as np

In [4]:
a1=np.array([1,3,5,7])
print(a1)

[1 3 5 7]


In [5]:
a2=np.array([[1,3,5,7],[2,4,6,8]])
print(a2)

[[1 3 5 7]
 [2 4 6 8]]


In [6]:
list=[1,2,3,4,5]
print(type(list))

<class 'list'>


In [7]:
a3=np.array(list)
print(type(a3))

<class 'numpy.ndarray'>


# Numpy Methods

In [8]:
#shape---Array Dimensions
#ndim---Number of dimentions
#data---Actual elements of the array
#size---Total number of arrya's  element
#dtype---type of elements
#itemsize---element's size in byte
#astype----changes the type of arrey elements

In [9]:
a2.shape

(2, 4)

In [10]:
a3.shape #no row/Column means 1 by defult

(5,)

In [11]:
a4=np.array([1.2])
a4.shape

(1,)

In [12]:
a2.dtype

dtype('int32')

In [13]:
a4.dtype

dtype('float64')

In [14]:
#there is a limitation here, you cannot define differant data types in one array:
a5=np.array([[1,2,3],[3,4,5.3]])
a5.dtype

dtype('float64')

In [15]:
#only sees first array becaus matrix elements are not equal
a6=np.array([[1,2,3],[4,5,6],[4,5,6,3]]) 
a6.shape

(3,)

In [16]:
a=np.array([1,2,2])

In [17]:
a.shape#an array of 3 items

(3,)

In [18]:
a=np.array([[1,2,2]])

In [19]:
a.shape#matrix

(1, 3)

In [20]:
a5.itemsize

8

In [21]:
a5.data

In [22]:
a7=np.array([[1,1],[3,3]],dtype=complex)

In [23]:
print(a7)

[[1.+0.j 1.+0.j]
 [3.+0.j 3.+0.j]]


In [24]:
a7.dtype

dtype('complex128')

In [25]:
a7.itemsize

16

In [26]:
a8=np.array([[1,1],[3,3.3]],dtype=int)

In [27]:
print(a8)

[[1 1]
 [3 3]]


In [28]:
a8.size# all the items

4

In [29]:
a8.astype(complex)

array([[1.+0.j, 1.+0.j],
       [3.+0.j, 3.+0.j]])

In [30]:
#copy----Copies the array
a9=a7.copy()
a9 is a7

False

In [97]:
#sort---sorts the elements
a10=np.array([[2,5,4,10],[30,4,5,1]])
print(a10)

[[ 2  5  4 10]
 [30  4  5  1]]


In [98]:
a11=np.sort(a10)
print(a11)

[[ 2  4  5 10]
 [ 1  4  5 30]]


In [99]:
a12=np.sort(a10,axis=0)
print(a12)

[[ 2  4  4  1]
 [30  5  5 10]]


In [34]:
a13=np.sort(a10,axis=0)
print(a10)

[[ 2  5  4 10]
 [30  4  5  1]]


In [35]:
print(np.sum(a10,axis=0))

[32  9  9 11]


In [36]:
print(np.sum(a10,axis=1))

[21 40]


In [37]:
a1=np.array((1,2,5)) #no differance
print(a1)

[1 2 5]


In [38]:
#making zero matrix
a2=np.zeros((2,5))
print(a2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [39]:
a3=np.zeros((1))
print(a3)

[0.]


In [40]:
#making zero matrix
a4=np.ones((2,3))
print(a4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [41]:
a5=np.ones((2,5,6))
print(a5)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


In [42]:
a6=np.ones((2,4),dtype=int)
print(a6)

[[1 1 1 1]
 [1 1 1 1]]


In [43]:
a7=np.arange(20)
print(a7)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [44]:
a8=np.arange(5,10)
print(a8)

[5 6 7 8 9]


In [45]:
a9=np.arange(1,10,0.5)
print(a9)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [46]:
a9.size

18

In [47]:
a10=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3) #3x3=9 else there is error
print(a10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
a11=np.array([1,2,3,4,5,6,7]).reshape(3,3) #gives you error

ValueError: cannot reshape array of size 7 into shape (3,3)

In [49]:
a12=np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(2,3,2)
print(a12)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [50]:
a12.ndim

3

In [51]:
a13=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3,1)
print(a13)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [52]:
a14=np.arange(60).reshape(3,2,10)
print(a14)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]]


In [53]:
a14.ndim

3

In [54]:
a15=np.arange(60).reshape(3,4,5)
print(a15)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [55]:
a16=np.array([1,3,5])
a17=np.array([2,4,6])

In [56]:
a18=np.vstack([a16,a17])
print(a18)

[[1 3 5]
 [2 4 6]]


In [57]:
a19=np.hstack([a16,a17])
print(a19)

[1 3 5 2 4 6]


# Copying Arrays

In [58]:
x=np.array([[1,3,5],[2,4,6],[8,9,10]])

In [59]:
xc1=x[0:2,1:3]
print(xc1)

[[3 5]
 [4 6]]


In [60]:
xc2=x[1,1]
print(xc2)

4


In [61]:
x[1,1]=44

In [62]:
print(x)

[[ 1  3  5]
 [ 2 44  6]
 [ 8  9 10]]


In [63]:
print(xc1)#changes in x changes thexc1

[[ 3  5]
 [44  6]]


In [64]:
xc2#it is not changed

4

In [65]:
xc3=+x[0:2,1:3]

In [66]:
print(xc3)

[[ 3  5]
 [44  6]]


In [67]:
x[1,1]=10

In [68]:
print(xc1)
print(xc3)

[[ 3  5]
 [10  6]]
[[ 3  5]
 [44  6]]


In [69]:
x=np.array([[1,2,3,4],[5,6,7,8]])

In [70]:
x.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [71]:
x.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [72]:
x.reshape(8)#if there is one argument it considers it as columns

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
x.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# Reading Elements

In [74]:
x=np.array([[1,2,3,4],[5,6,7,8]])

In [75]:
for i in x:
    print(i)

[1 2 3 4]
[5 6 7 8]


In [76]:
#3 ways to get elements:
y=x.reshape(8)
for i in y:
    print(i,end=" ")

1 2 3 4 5 6 7 8 

In [77]:
#3 ways to get elements:
for i in x:
    for j in i:
        print(j,end=" ")

1 2 3 4 5 6 7 8 

In [78]:
#3 ways to get elements:
x.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
for i in x.ravel():
    print(i,end=" ")

1 2 3 4 5 6 7 8 

In [80]:
z=np.array([2,4,6,8])

In [81]:
i=iter(z)

In [82]:
n=next(i)

In [83]:
print(n)

2


# Mathematic Operations in arrays

In [84]:
z=np.array([2,4])
w=np.array([2,3])
z+w

array([4, 7])

In [85]:
a=np.array([[2,4,6],[2,4,6]])
b=np.array([[3,4,5],[3,4,5]])

In [86]:
a*b

array([[ 6, 16, 30],
       [ 6, 16, 30]])

In [87]:
z=np.array([[2,4,6],[1,2,3]]) #2x3
w=np.array([[2,3],[4,5],[5,6],[4,5]])#4x2

In [88]:
np.dot(w,z)

array([[ 7, 14, 21],
       [13, 26, 39],
       [16, 32, 48],
       [13, 26, 39]])

In [91]:
u=np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [92]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

In [94]:
i=j@j
i

array([[-1.,  0.],
       [ 0., -1.]])